#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend stezzy.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 147637-web-01 54.234.63.197:80
        server 147637-web-02 52.87.232.156:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
